### ISSUE TITLE
你不使用模板进行提问. 我很难给你解决问题

### ISSUE THREAD

**Issue by cndaqiang** [cndaqiang/WZRY#68]
![image](https://github.com/user-attachments/assets/12e4b8b7-f5de-4763-b796-db9a045ac1ae)

如果你完成这些内容, 请在`[ ]`内打上`x`, 即`[x]`
- [x] 我已阅读全新的[项目主页](https://cndaqiang.github.io/wzry.doc/)
- [x] 我已阅读全新的[安装指南](https://cndaqiang.github.io/wzry.doc/guide/install/)
- [x] 我已查看[常见问题收录](https://cndaqiang.github.io/wzry.doc/QA/), 并未找到重复问题
- [x] 我已升级脚本和依赖为[最新的版本](https://github.com/cndaqiang/WZRY/releases)
- [x] 我已可以顺利控制一台模拟器进行对战

## 为了快速解决问题，请尽可能的提供这些内容，并礼貌**友善**的提问
* 如果你可以为本项目点个[star](https://github.com/cndaqiang/WZRY), 我会更愉快的回答你的问题.

### 软件自2.2.0以来经历了巨大的更新, 版本小于2.2.0遇到的issues不予回复
* 建议采用最新的[stable版本](https://github.com/cndaqiang/WZRY/releases),至少也要[2.2.8](https://github.com/cndaqiang/WZRY/releases/tag/2.2.8)以上

### 配置文件截图
> 请在此处上传你的配置文件`config.win.yaml`截图或者粘贴到此处

例如我的配置文件
```
#client
# 仅在单进程时有效
mynode: 0
# 多进程时，多进程的数目
totalnode: 2
# 多进程配置
multiprocessing: True
#默认读入字符串, 不要添加引号
BlueStackdir: C:\Program Files\BlueStacks_nxt
BlueStack_Instance:
    0: Pie64_1
    1: Pie64
BlueStack_Windows:
    0: BlueStacks1
    1: BlueStacks0
#
LINK_dict:
    0: Android:///127.0.0.1:5565
    1: Android:///127.0.0.1:5555
#
#control:
#prefix: wzry
logger_level: 0
#outputnode: 0
figdir: assets
logfile:
    0: result.0.txt
    1: result.1.txt
```

### 执行结果
> 请在此处上传你的执行结果截图或者粘贴到此处
> 或者cmd/powershell/terminal/vscode/pycharm等运行界面报错等截图

例如我上传的执行结果

![image](https://github.com/user-attachments/assets/86562c4b-49c9-432a-bfef-415bcb5499dc)
[result.0.txt](https://github.com/user-attachments/files/17788598/result.0.txt)

### 运行目录
> 请在此处粘贴你的代码目录截图
例如
![image](https://github.com/user-attachments/assets/a2eb219b-f485-44fe-bff2-a2a757f3999c)

### 模拟器设置页面
* 请在此处粘贴你的模拟器设置页面.
* 需要确定你开启了ADB以及ADB的端口以及分辨率和dpi的设置.
* 非`960x540`分辨率`dpi=160`的设备, 请自行解决.

例如
![image](https://github.com/user-attachments/assets/ce5ca8ce-c1a2-4ac0-a2e3-e1b3ad74f5e0)

### 游戏页面
请在此处粘贴你的游戏页面.
